# https://dev.azure.com/home-assistant

trigger:
  branches:
    include:
    - master
  tags:
    include:
    - '*'
    exclude:
    - untagged*
pr:
- master

variables:
  - name: versionHadolint
    value: 'v1.16.3'
  - name: versionBuilder
    value: '3.1'
  - group: docker

jobs:

- job: 'Tox'
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python $(python.version)'
    inputs:
      versionSpec: '3.7'
  - script: pip install tox
    displayName: 'Install Tox'
  - script: tox
    displayName: 'Run Tox'


- job: 'Hadolint'
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: sudo docker pull hadolint/hadolint:$(versionHadolint)
    displayName: 'Install Hadolint'
  - script: |
      sudo docker run --rm -i \
        -v $(pwd)/.hadolint.yaml:/.hadolint.yaml:ro \
        hadolint/hadolint:$(versionHadolint) < Dockerfile
    displayName: 'Run Hadolint'


- job: 'ReleaseDEV'
  condition: and(eq(variables['Build.SourceBranchName'], 'master'), succeeded('Tox'), succeeded('Hadolint'))
  dependsOn:
  - 'Tox'
  - 'Hadolint'
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: sudo docker login -u $(dockerUser) -p $(dockerPassword)
    displayName: 'Docker hub login'
  - script: sudo docker pull homeassistant/amd64-builder:$(versionBuilder)
    displayName: 'Install Builder'
  - script: |
      sudo docker run --rm --privileged \
        -v ~/.docker:/root/.docker \
        -v /run/docker.sock:/run/docker.sock:rw -v $(pwd):/data:ro \
        homeassistant/amd64-builder:$(versionBuilder) \
        --builder-wheels --version dev --all \
        -t /data --docker-hub homeassistant
    displayName: 'Build DEV'


- job: 'Release'
  condition: and(startsWith(variables['Build.SourceBranch'], 'refs/tags'), succeeded('Tox'), succeeded('Hadolint'))
  dependsOn:
  - 'Tox'
  - 'Hadolint'
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: sudo docker login -u $(dockerUser) -p $(dockerPassword)
    displayName: 'Docker hub login'
  - script: sudo docker pull homeassistant/amd64-builder:$(versionBuilder)
    displayName: 'Install Builder'
  - script: |
      sudo docker run --rm --privileged \
        -v ~/.docker:/root/.docker \
        -v /run/docker.sock:/run/docker.sock:rw -v $(pwd):/data:ro \
        homeassistant/amd64-builder:$(versionBuilder) \
        --builder-wheels --all -t /data --docker-hub homeassistant
    displayName: 'Build Release'